#pragma once

#define PIPELINE_ITEM_NAME_LENGTH 64
// #define SEMANTIC_LENGTH 32
#define VARIABLE_NAME_LENGTH 256
#define MAX_RENDER_TEXTURES 16

#define MODEL_GROUP_NAME_LENGTH 64

#define SDL_GLSL_VERSION "#version 330"

#define SHADERED_DESKTOP
// #define SHADERED_WEB
#define SHADERED_VERSION 1005005

#define DEBUG_ID_START 1
#define DEBUG_PRIMITIVE_GROUP 170
#define DEBUG_INSTANCE_GROUP 512

#ifdef _WIN32
#define SHADERED_MAX_PATH 260
#else
#define SHADERED_MAX_PATH 512
#endif